### ISSUE TITLE
module 'warp' has no attribute 'scale'

### ISSUE THREAD

**Issue by bkersbergen** [n-s-f/warp#2]
When running the notebook it fails on several methods in the warp.py, for example:
_scaled_sin = warp.scale(np.sin, [.3, .6], [2, 5, 1, 6], np.pi*2)
plt.plot(x, scaled_sin(x));_
with error:
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c2f65cc34b06> in \<module\>()
 1 scaled_sin = warp.scale(np.sin, [.3, .6], [2, 5, 1, 6], np.pi*2)
 2 plt.plot(x, scaled_sin(x));
AttributeError: module 'warp' has no attribute 'scale'

It seems like the following functions are missing in warp.py:
- scale
- generate_distortion_function
- generate_scale_function
- fscale
- warp
- fwarp

**Comment by n-s-f** [comment]
Thanks for opening the issue! I'll update the demo notebook tonight. 

In the meanwhile, the functions you're looking for have all been renamed:


scale -> linear_scale
generate_distortion_function -> generate_linear_distortion
generate_scale_function -> generate_linear_scale
fscale -> functional_scale
warp -> linear_warp
fwarp -> functional_warp

I renamed them to allow for other kinds of warping and scaling, e.g. spline and bezier curves, which have the same function signatures as their linear counterparts but behave differently.

**Comment by n-s-f** [comment]
I've updated the demo so that everything should work, and pushed the updates to pypi. I'll update the documentation shortly to cover the more recently added functionality.

**Comment by bkersbergen** [comment]
Thanks for the quick response.
After commenting out line 3 (import bezier) in bezier.py it works like a charm!
